name: Agent Exports
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with: { php-version: '8.2' }
      - run: composer install --no-interaction --prefer-dist || true
      - run: php agent/scripts/export_project.php > agent/exports/project_manifest.json || true
      - run: php agent/scripts/export_models.php > agent/exports/models.json || true
      - run: php agent/scripts/export_env.php > agent/exports/env_meta.json || true
      - run: node agent/scripts/export_common.mjs || true
      - run: node agent/scripts/detect_stack.mjs > agent/exports/signals.json || true
      - run: node agent/scripts/synthesize.mjs || true
      - run: bash agent/scripts/run_phpstan.sh || true
      - run: bash agent/scripts/run_rector_dry.sh || true
      - run: bash agent/scripts/run_deptrac.sh || true
      - run: bash agent/scripts/run_metrics.sh || true
      - uses: actions/upload-artifact@v4
        with:
          name: agent-exports
          path: agent/exports
